# 数组的运算函数

In [65]:
import numpy as np

## 求和

In [66]:
a = np.array([[1,2,3],
         [4,5,6]])

求所有元素的和  
注意使用numpy中sum函数而不是python自带的sum函数

In [67]:
print(a.sum())
print(np.sum(a))
print(sum(a))


21
21
[5 7 9]


使用切片进行求和,  
求2,3列的和

In [81]:
a[:,1:3].sum()
print(type(a))

<class 'numpy.ndarray'>


## 沿着轴求和
针对类ndarray的运算方法都可以沿着轴计算

沿着第一维求和

In [69]:
a.sum(axis=0)

array([5, 7, 9])

沿着第二维求和

In [70]:
a.sum(axis=1)

array([ 6, 15])

## 求积
求取所有元素的积

In [71]:
print(np.prod(a))
print(a.prod())

720
720


## 求最大和最小值

In [72]:
a = np.random.rand(4,5)
print(a)

[[ 0.22565632  0.77936579  0.83553875  0.88232853  0.42280475]
 [ 0.77042327  0.1283714   0.31660622  0.40448403  0.65181329]
 [ 0.31676527  0.29651153  0.86954282  0.59085923  0.91354412]
 [ 0.78778664  0.39658387  0.64964622  0.46242778  0.08785658]]


In [73]:
print(a.min())

0.0878565849764


In [74]:
print(a.max())

0.913544118343


使用切片求取局部最小，最大

In [75]:
print(a[0:2,2].min())
print(a[0:-1,-2].max())

0.316606215596
0.882328525399


使用花式索引  
第2,4行的第3,４个元素最大最小

In [76]:
print(a[:,(1,3)][(2,3),:].min())
print(a[:,(1,3)][(2,3),:].max())

0.296511530811
0.590859231927


沿着轴的最大最小

In [77]:
a.min(axis=0)

array([ 0.22565632,  0.1283714 ,  0.31660622,  0.40448403,  0.08785658])

In [78]:
a.max(axis=-1)

array([ 0.88232853,  0.77042327,  0.91354412,  0.78778664])

## 最大最小值的位置
argmin,argmin方法

In [82]:
a.argmin()

0

In [85]:
a.argmax(axis=1)

array([2, 2])

## 均值
使用mean()方法

In [79]:
a = np.array([[1,2,3],[4,5,6]])

In [86]:
a.mean()

3.5

也可以使用average函数，average函数还支持加权平均

In [87]:
np.average(a)

3.5

In [88]:
np.average(a,axis=0)

array([ 2.5,  3.5,  4.5])

In [95]:
np.average(a, axis=1, weights=[1,2,3])

array([ 2.33333333,  5.33333333])

## 标准差
用std方法计算标准差

In [96]:
a.std()

1.707825127659933

In [97]:
a.std(axis=1)

array([ 0.81649658,  0.81649658])

var方法计算方差

In [98]:
a.var(axis=0)

array([ 2.25,  2.25,  2.25])

也可以使用函数var,std

## clip 方法
将数值限制在一个范围内

In [99]:
a = np.array([[1,2,3],[4,5,6]])

In [100]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

## ptp 方法
计算最大与最小值的差值

In [101]:
a.ptp()

5

In [102]:
a.ptp(axis=0)

array([3, 3, 3])

## round 方法
近似，默认到整数

In [103]:
a = np.array([1.35, 2.5, 1.5])

In [104]:
a.round()

array([ 1.,  2.,  2.])

近似到一位小数

In [107]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])