# 数组类型

In [2]:
import numpy as np

之前我们在第一章使用过整形，浮点型，布尔型数组  
## 复数数组
产生一个复数数组

In [4]:
a = np.array([1+1j, 2, 3, 4-2j])
print(a)

[ 1.+1.j  2.+0.j  3.+0.j  4.-2.j]


查看数组的元素类型

In [5]:
print(a.dtype)

complex128


对于复数可以查看它的实部和虚部

In [7]:
print(a.real)
print(a.imag)

[ 1.  2.  3.  4.]
[ 1.  0.  0. -2.]


还可以设置他们的数值

In [10]:
a.imag = [0, 1, 2, 3]
print(a)

[ 1.+0.j  2.+1.j  3.+2.j  4.+3.j]


查看共轭

In [11]:
print(a.conj())

[ 1.-0.j  2.-1.j  3.-2.j  4.-3.j]


实际上，在浮点和整形数组上也可以使用这些函数  
但是虚部只可读，不能修改数值

In [12]:
a = np.array(range(5))
print(a.dtype)

int64


In [13]:
print(a.real)
print(a.imag)
print(a.conj())

[0 1 2 3 4]
[0 0 0 0 0]
[0 1 2 3 4]


## 制定数组类型

### <center>numpy的数据类型</center>  

类型|说明|字节数
:-|:-|-
int8,uint8|有符号无符号8位整型|1
int16,unit16|有符号无符号16位整型|2
int32,unit32|有符号无符号32位整型|4
int64,unit64|有符号无符号64位整型|8
float16|半精度浮点型|-
float32|单精度浮点型，与C的float兼容|-
float64|双精度浮点型，与C的double兼容|-
float128|扩展精度浮点型|-
complex64,complex128|两个64,128位浮点数表示复数|-
bool|ture和false|-
object|对象，数组中可以使用任意值|-
viod|records|-

之前构造数组时，数组会根据内容自动判断类型


In [19]:
a = np.array([0.,1,2,3,4])
print(a.dtype)
# 4bytes*5
print(a.nbytes)

float64
40


也可以手动的指定类型

In [32]:
a = np.array([0 ,1 ,2 ,3 ,4], dtype = np.float32)
print(a.dtype)

float32


0-225的数字可以表示ASCII码，我们可以用ord函数查看字符的ASCII码值

In [55]:
print(ord('f'))
print(ord('S'))

102
83


任意值类型数组

In [57]:
a = np.array([1, 1.2, 'hello', [1, 2 ,3]], dtype = object)
print(a)

[1 1.2 'hello' list([1, 2, 3])]


乘法

In [60]:
print(a*2)
print(type(a))
print(a.dtype)

[2 2.4 'hellohello' list([1, 2, 3, 1, 2, 3])]
<class 'numpy.ndarray'>
object


## 类型转换
转换数组的类型

In [62]:
a = np.array([1.5, 3, -2],dtype = np.float32)
print(a)

[ 1.5  3.  -2. ]


### asarray函数

In [65]:
b = np.asarray(a, dtype=np.float64)
print(b.dtype)

float64


asarray不会改变数值，但是因为数据溢出导致数值变化

In [68]:
print(np.asarray(a, dtype=np.uint8))

[  1   3 254]


当类型相同的时候，asarray不会产生新的对象，而是对一个引用  
其实当改变数据类型时，数据内存会发生变化，其原因是分配了新的内存。

In [70]:
print(b is a)
b = np.asarray(a, dtype=np.float32)
print(b is a)

False
True


asarray不仅可以作用于数组，还可以将其他类型转换为数组。  
有些时候为了保证输入是数组，我们需要使用asarray进行转化，它原本为数组时不会产生新对象

In [73]:
np.asarray([1, 2, 3, 4])


array([1, 2, 3, 4])

### astype函数

In [76]:
a.astype(np.float64).dtype


dtype('float64')

In [78]:
a.astype(np.uint8).dtype

dtype('uint8')

astype总是返回原来数组的一份赋值，即使转换的类型相同

In [79]:
b = a.astype(np.float32)
print(a is b)

False


### view 方法

In [83]:
a =np.array([1, 2, 3,4], dtype=np.int32)
print(a.dtype)

int32


view会将a在内存中表示看做是uint8进行解析  
不会改变数据的内容

In [87]:
b = a.view(np.uint8)
print(b)
print(a is b)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0]
False


两者公用同一块内存，只是数据解析的方式不同

In [90]:
a[0] = 2**10
print(a)
print(b)

[1024    2    3    4]
[0 4 0 0 2 0 0 0 3 0 0 0 4 0 0 0]
